# GCC-9
# apt-get install software-properties-common
# apt-add-repository
# apt-get update
# apt-get install gcc-9 g++-9

- name: gcc - deps
  apt:
    package:
      - software-properties-common

- name: gcc - add repo
  apt_repository:
    repo: ppa:ubuntu-toolchain-r/test
    state: present

- name: gcc - install
  apt:
    package:
      - gcc-9
      - g++-9